repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    -   id: trailing-whitespace
    #-   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: double-quote-string-fixer
    -   id: debug-statements
    -   id: check-toml
    -   id: check-json
    -   id: check-xml


# - repo: https://github.com/pycqa/isort
#   rev: v5.11.3
#   hooks:
#     - id: isort
#       name: isort (python)
# - repo: https://github.com/PyCQA/bandit
#   rev: 1.7.4
#   hooks:
#   -   id: bandit
#       exclude: ^tests/
# - repo: https://github.com/psf/black
#   rev: 22.12.0
#   hooks:
#   -   id: black
# - repo: https://github.com/pycqa/flake8
#   rev: 6.0.0
#   hooks:
#   -   id: flake8
#       exclude: ^tests/
