name: core-infra

trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnectionName: core-dev-sc
  resourceGroupName: rg-core-dev-001

stages:
- stage:
  displayName: Dev
  jobs:
    - job:
      displayName: Dev Deployment
      steps:
        - task: AzureCLI@1
          displayName: "Deploy - Infra"
          name: "Create_Infra"
          inputs:
            azureSubscription: $(serviceConnectionName)
            scriptLocation: "inlineScript"
            inlineScript: |
              az deployment group create \
              --name core-deployment \
              --resource-group $(resourceGroupName) \
              --template-file "$(System.DefaultWorkingDirectory)/templates/main.bicep" \
              --parameters "$(System.DefaultWorkingDirectory)/parameters/infra.dev.json"
